// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgkBCs0uGb15GNMxM4ldiihGpGP7fD3iQ',
    appId: '1:866323323234:web:2c7563c8faa9ac6e4d343b',
    messagingSenderId: '866323323234',
    projectId: 'nelayannet-b2bd6',
    authDomain: 'nelayannet-b2bd6.firebaseapp.com',
    storageBucket: 'nelayannet-b2bd6.appspot.com',
    measurementId: 'G-7M33RPDCFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZJm2_goLioWq5T0sYtKAfRm-_Hht4sMY',
    appId: '1:866323323234:android:54209ddb91da08144d343b',
    messagingSenderId: '866323323234',
    projectId: 'nelayannet-b2bd6',
    storageBucket: 'nelayannet-b2bd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5K9TD3uaQaA9zu8WFv8Kbcy7PQwWtpCg',
    appId: '1:866323323234:ios:b60308a7aeaa4cc84d343b',
    messagingSenderId: '866323323234',
    projectId: 'nelayannet-b2bd6',
    storageBucket: 'nelayannet-b2bd6.appspot.com',
    iosBundleId: 'com.example.nelayannet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgkBCs0uGb15GNMxM4ldiihGpGP7fD3iQ',
    appId: '1:866323323234:web:1e48319739485b564d343b',
    messagingSenderId: '866323323234',
    projectId: 'nelayannet-b2bd6',
    authDomain: 'nelayannet-b2bd6.firebaseapp.com',
    storageBucket: 'nelayannet-b2bd6.appspot.com',
    measurementId: 'G-22FKJMVCC8',
  );
}
